CREATE TABLE MODEL (
    ModelNo INTEGER PRIMARY KEY,
    Capacity INTEGER NOT NULL,
    Weight REAL NOT NULL
);

CREATE TABLE PLANE (
    RegNo TEXT PRIMARY KEY,
    ModelNo INTEGER,
    FOREIGN KEY (ModelNo) REFERENCES MODEL(ModelNo)
);

CREATE TABLE EMPLOYEES (
    SSN TEXT PRIMARY KEY,
    Name TEXT NOT NULL,
    UnionMemNo INTEGER NOT NULL
);

CREATE TABLE TECHNICIAN (
    SSN TEXT PRIMARY KEY,
    Address TEXT,
    Phone TEXT,
    Salary REAL,
    FOREIGN KEY (SSN) REFERENCES EMPLOYEES(SSN)
);

CREATE TABLE TRAFFICCONT (
    SSN TEXT PRIMARY KEY,
    ExamDate DATE,
    FOREIGN KEY (SSN) REFERENCES EMPLOYEES(SSN)
);

CREATE TABLE EXPERT (
    SSN TEXT,
    ModelNo INTEGER,
    PRIMARY KEY (SSN, ModelNo),
    FOREIGN KEY (SSN) REFERENCES TECHNICIAN(SSN),
    FOREIGN KEY (ModelNo) REFERENCES MODEL(ModelNo)
);

CREATE TABLE TEST (
    FAANo INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Score INTEGER
);

CREATE TABLE TESTINFO (
    RegNo TEXT,
    SSN TEXT,
    FAANo INTEGER,
    Hours REAL,
    Date DATE,
    Score INTEGER,
    PRIMARY KEY (RegNo, SSN, FAANo),
    FOREIGN KEY (RegNo) REFERENCES PLANE(RegNo),
    FOREIGN KEY (SSN) REFERENCES TECHNICIAN(SSN),
    FOREIGN KEY (FAANo) REFERENCES TEST(FAANo)
);
